### ISSUE TITLE
"Npm start" on backend server not working

### ISSUE THREAD

**Issue by Ryu-From-Streets** [Ryu-From-Streets/classcompass#14]
Running "npm start" on the backend no longer works. It throws the error:

```
Error: Cannot find module '...\classcompass\backend\app.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

It seems like app.js is deleted and presumably no longer being used, however the script command to run the backend still uses app.js causing the error. 
This script should be updated in "/backend/package.json" to reflect the correct module the backend is now running, as soon as possible.

**Comment by terminal-lucidity** [comment]
fixed!
