### ISSUE TITLE
Login and Registration Page

### ISSUE THREAD

**Issue by Ryu-From-Streets** [Ryu-From-Streets/classcompass#15]
Implement a login and registration page for beta release.

**Comment by terminal-lucidity** [comment]
Progress until now:
1. We have our login, sign-up, and forgot password pages set up
2. We have linked them
3. We have added basic type checks

To be completed:
1. Integration with backend
2. Testing
3. Remember-me feature

**Comment by terminal-lucidity** [comment]
Hi! 
I have gone back on my original plan a little bit. But I am planning to move the student detail fields to a different page, will keep you posted.
