### ISSUE TITLE
Course Tree Page

### ISSUE THREAD

**Issue by Ryu-From-Streets** [Ryu-From-Streets/classcompass#16]
Implement a course tree page for beta release, that displays course prerequisites as a node tree.

**Comment by ngordonumass** [comment]
Progress so far:

Node tree is calculated and displayed, however a known bug is that the rendered tree isn't user friendly and needs work.
Each course in then node tree can be clicked on and redirects you back to the TreePage. However, a know bug with this feature is that for some reason the node tree isn't correctly calculated or displayed in this case.

**Comment by ngordonumass** [comment]
Current Progress:

Render Tree UI is now much more use friendly. Currently, you can no longer click on each node to see that course's prerequisites. However, there is a zoom and drag feature that will be convenient for larger trees. One known bug is that with the way prerequisite data is currently handled. It can accurately handle situation where you can take one course from a list of courses to fill the same prerequisite requirement. However, if there are multiple different ways to fill the same prerequisite the rendered tree won't accurately show this. For example, if for a course (let's call it CS102) had the prerequisites of CS101 OR CS100 and Math101 then the tree will simply display as though you need to take all three courses. But if instead, the prerequisites for CS102 was CS101 and either CS100 or Math101. Then the tree actually would display this accurately (CS101 and any of [CS100, Math101])

**Comment by ngordonumass** [comment]
Beta release completed. Render tree was not always 100% accurate at the time of the beta release. Now with the 1.0 release the render trees should be accurate 100% of the time.
