### ISSUE TITLE
Feature Note: No clear button for new prerequisite query, have to back arrow to navigate the tree page

### ISSUE THREAD

**Issue by NFordUMass** [Ryu-From-Streets/classcompass#47]
<img width="577" alt="Screenshot 2024-04-26 at 16 36 39" src="https://github.com/Ryu-From-Streets/classcompass/assets/113483306/1883ca0b-4004-4ad9-9cec-1e478c2fbc61">

**Comment by Ryu-From-Streets** [comment]
Issue resolved through explicit link on tree page that takes user back to search/home page.
