### ISSUE TITLE
BACKEND: No route for getting advisor by id

### ISSUE THREAD

**Issue by Ryu-From-Streets** [Ryu-From-Streets/classcompass#59]
There is currently no route for getting an advisor by id.

A method for doing so seems to be defined in controllers/advisor.js but it isn't referenced in routes/advisor.js, so there is currently no way for the frontend to fetch advisors by id which is needed for some frontend functionality eventually.

Ultimately this isn't super pressing as the major concern is student account functionality, and routes for getting students by id are implemented.

This doesn't seem too difficult of a fix however, so whenever anybody gets a chance, it would be appreciated.

**Comment by LastSpot** [comment]
added the route for getting advisor by id
