### ISSUE TITLE
BACKEND: Not sending user id back in response when handling student and advisor sign ups

### ISSUE THREAD

**Issue by Ryu-From-Streets** [Ryu-From-Streets/classcompass#60]
Currently in the handleSignUp functions in both controllers/advisor.js and controllers/student.js do not send back user._id in the response.

This is needed by the frontend in order to make called to the students/:id and advisors/:id routes to fetch/modify/delete user accounts.

This should be fixed ASAP as it is needed for major features such as marking courses as taken as a student (and thus color coding), and modifying courses as an advisor. This doesn't seem to be too difficult to fix, just in the response also send back a key value pair containing user._id as a value. Thank you.

**Comment by LastSpot** [comment]
done, added user id
