### ISSUE TITLE
Auto collapse course tree after 3 layers

### ISSUE THREAD

**Issue by Ryu-From-Streets** [Ryu-From-Streets/classcompass#69]
Current course tree can get unwieldy when there are a lot of prerequisites. Implement auto collapse after 3 layers to maximize information shown without overwhelming the user with the entire tree. Nodes should still be expandable allowing users to still view more of the tree if they wish. But by default it should only show 3 layers.

**Comment by ngordonumass** [comment]
Prerequisite tree now collapses after 3 layers
